SELECT SB.AUTHOR_ID, A.AUTHOR_NAME, SB.CATEGORY, SUM(SB.PRICE * SB.SALES) AS TOTAL_SALES
FROM AUTHOR AS A
LEFT JOIN 
(
    SELECT B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY, B.PRICE, SALE.SALES
    FROM
        (
        SELECT BOOK_ID, SALES
        FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
        ) AS SALE
    RIGHT JOIN BOOK AS B
    ON SALE.BOOK_ID = B.BOOK_ID
) AS SB
ON SB.AUTHOR_ID = A.AUTHOR_ID
GROUP BY SB.AUTHOR_ID, SB.CATEGORY
ORDER BY SB.AUTHOR_ID ASC, SB.CATEGORY DESC

